In [1]:
# resources
import sys
sys.path.append("../../py/")
from spacecraft import spacecraft
from indirect.dynamics import dynamics
import numpy as np
import PyKEP as pk

In [2]:
# instantiate spacecraft
sc = spacecraft()

In [3]:
# instantiate dynamics
dyn = dynamics(sc)

In [4]:
# instantiate planet
p = pk.planet.jpl_lp('mars')

# get example state
r, v = np.asarray(p.eph(5433))
m = sc.mass

# nondimensionalise state
r /= dyn.L
v /= dyn.V
m /= dyn.M

# random standard normal costates
l = np.random.randn(7)

# assemble example fullstate
fs = np.hstack((r, v, [m], l))

# print
print("Example Nondimensional Fullstate =\n" + str(fs))

Example Nondimensional Fullstate =
[  1.05157363e+00  -9.02413393e-01  -4.47208637e-02   5.60664535e-01
   6.86970892e-01   6.31631259e-04   1.00000000e+00   2.18848787e+00
   4.44380170e-01  -6.39048453e-01   1.71131983e+00  -1.43855538e+00
   8.25849610e-01   1.27863924e+00]


In [5]:
# compute unbounded quadratic controls from Pontryagin
dyn.alpha = 0
dyn.bound = False
qubc = dyn.pontryagin(fs)

# compute bounded quadratic controls from Pontryagin
dyn.bound = True
qc = dyn.pontryagin(fs)

# compute mass optimal controls from Pontryagin
dyn.alpha = 1
mc = dyn.pontryagin(fs)

# print
print("Controls: [throttle, x-dir, y-dir, z-dir]")
print("Unbounded Quadratic Control =\n" + str(qubc))
print("Bounded Quadratic Control =\n" + str(qc))
print("Mass Optimal Control =\n" + str(mc))

Controls: [throttle, x-dir, y-dir, z-dir]
Unbounded Quadratic Control =
[ 0.00331925 -0.71804849  0.60359993 -0.34651621]
Bounded Quadratic Control =
[ 0.00331925 -0.71804849  0.60359993 -0.34651621]
Mass Optimal Control =
[ 0.         -0.71804849  0.60359993 -0.34651621]


In [6]:
# compute Hamiltonian (not needed)
H = dyn.hamiltonian(fs)
print("Hamiltionian = " + str(H))

Hamiltionian = 0.383318808405


In [7]:
# compute fullstate transition
dfs = dyn.eom_fullstate(fs)
print("Fullstate Rate of Change =\n" + str(dfs))

Fullstate Rate of Change =
[  5.60664535e-01   6.86970892e-01   6.31631259e-04  -3.94599386e-01
   3.38627521e-01   1.67813502e-02  -0.00000000e+00  -1.24289789e+00
   1.07786520e+00   3.90064435e-01  -2.18848787e+00  -4.44380170e-01
   6.39048453e-01  -0.00000000e+00]


In [8]:
# compute fullstate transition Jacobian
ddfs = dyn.eom_fullstate_jac(fs)
print("Fullstate Rate of Chance Jacobian =\n" + str(ddfs))

Fullstate Rate of Chance Jacobian =
[[ 0.          0.          0.          1.          0.          0.          0.
   0.          0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          1.          0.          0.
   0.          0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.          0.
   0.          0.          0.          0.          0.          0.          0.        ]
 [ 0.27238573 -0.55576903 -0.02754222  0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.          0.        ]
 [-0.55576903  0.10168953  0.0236355   0.          0.          0.         -0.
   0.          0.          0.          0.          0.          0.          0.        ]
 [-0.02754222  0.0236355  -0.37407526  0.          0.          0.          0.
   0.          0.          0.          0.          0.        